"""idempotency table

Revision ID: 6292d1d97bb2
Revises: a29755ffadf4
Create Date: 2026-06-23 16:42:12.136046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6292d1d97bb2'
down_revision: Union[str, None] = 'a29755ffadf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskiq_task_executions',
    sa.Column('execution_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('taskiq_task_id', sa.String(length=64), nullable=False),
    sa.Column('task_args_hash', sa.String(length=64), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_taskiq_task_executions_task_name'), 'taskiq_task_executions', ['task_name'], unique=False)
    op.create_index(op.f('ix_taskiq_task_executions_taskiq_task_id'), 'taskiq_task_executions', ['taskiq_task_id'], unique=False)
    op.create_index('ix_tte_hash_status', 'taskiq_task_executions', ['task_args_hash', 'status'], unique=False)
    op.create_index('ix_tte_name_enqueued', 'taskiq_task_executions', ['task_name', 'enqueued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tte_name_enqueued', table_name='taskiq_task_executions')
    op.drop_index('ix_tte_hash_status', table_name='taskiq_task_executions')
    op.drop_index(op.f('ix_taskiq_task_executions_taskiq_task_id'), table_name='taskiq_task_executions')
    op.drop_index(op.f('ix_taskiq_task_executions_task_name'), table_name='taskiq_task_executions')
    op.drop_table('taskiq_task_executions')
    # ### end Alembic commands ###
